Fs = 2000000;
filtertype = 'FIR';
Fpass = 2000;
Fstop = 1000;
Rp = 0.1;
Astop = 60;
HighpassFilter = dsp.HighpassFilter(SampleRate=Fs,...
    FilterType=filtertype,...
    PassbandFrequency=Fpass,...
    StopbandFrequency=Fstop,...
    PassbandRipple=Rp,...
    StopbandAttenuation=Astop);

% fvtool(HighpassFilter,Analysis='freq') %uncomment to graph the filter