Fs = 200000; 
filtertype = 'FIR';
Fpass = 90000;
Fstop = 85000; 
Rp = 0.1;
Astop = 80;
FIRHPF = dsp.HighpassFilter(SampleRate=Fs,...
                             FilterType=filtertype,...
                             PassbandFrequency=Fpass,...
                             StopbandFrequency=Fstop,...
                             PassbandRipple=Rp,...
                             StopbandAttenuation=Astop);

fvtool(FIRHPF,Analysis='freq')