Fs = 10000000; 
filtertype = 'FIR';
Fpass = 10000;
Fstop = 5000; 
Rp = 0.1;
Astop = 60;
FIRHPF = dsp.HighpassFilter(SampleRate=Fs,...
                             FilterType=filtertype,...
                             PassbandFrequency=Fpass,...
                             StopbandFrequency=Fstop,...
                             PassbandRipple=Rp,...
                             StopbandAttenuation=Astop);

fvtool(FIRHPF,Analysis='freq')